###############################
#  EndMinecraftPlusV2         #
#   Designed by SerendipityR  #
###############################

CfgVer: 7

AttackSettings:
  Address: "example.com"
  Port: 25565
  # 攻击方式:
  # 1 - BotAttack - 集群假人(代理)
  # 2 - MotdAttack - MOTD压测(无代理)
  # 3 - MotdAttackP - MOTD压测(代理)
  # 4 - DoubleAttack - 影分身攻击(代理，仅原版单服可用)
  # 5 - BotDebug - 假人调试模式(无代理)
  Method: 1
  Time: 3600
  ConnectDelay: 15
  ConnectTimeout: 5000
  # 实际连接数由代理质量和机器性能有关
  # 进行无代理Motd压测时不建议大于32
  MaxConnections: 2500
  # 旧版漏洞利用，大概率无效
  AntiAttackMode: true
  DoubleExploitPlayer: "ImOldSix_666"
  # 假人调试模式
  DebugPlayer: "Genshin_Activate"
  DebugPlayerActivities:
    Enable: true
    # 调试流程
    # wait - 等待:<时间(ms)>
    # chat - 发送聊天信息:<内容>
    # randomTeleport - 随机传送:<次数>
    # backTeleport - 回到重生点
    # register&Login - 执行注册/登录:<密码>
    # crashPacket - 发送崩服数据包:<数量>
    Actions:
      - "wait:1000"
      - "chat:原神，启动!"
      - "randomTeleport:1"
      - "wait:1000"
      - "backTeleport"
      - "register&Login:genshinImpact"
      - "crashPacket:20"
      - "wait:1000"
      - "crashPacket:20"
  ShowFails: false

AdvancedSettings:
  # 启用Forge支持
  ForgeSupport:
  # 从mods文件夹中读取modId:version信息
    Enable: true
    ReadFromFiles: true
    ModList:
      - "exampleMod:1.0.0"
  # 猫反作弊欺骗
  CatAntiCheat:
    Enable: false
    CustomScreenShot: "test.png"
    # 类加载列表，请注意版本特征
    # 1.7.10 - net.minecraft.launchwrapper.ITweaker
    # 1.12.2 - net.minecraft.launchwrapper.LaunchClassLoader
    LoadedClass:
      - "net.minecraft.launchwrapper.LaunchClassLoader"
    # 需在mods文件夹中放入5个以上原始客户端模组
    LoadedMods: "mods"
  # MAC|Check欺骗
  MACChecker:
    RandomMAC: false
  # 发 包 崩 服
  # 来自FDPClient的魔法道具~
  ServerCrasher:
    # 1 - Book (BSign/BEdit) [仅1.12.2前可用]
    # 2 - Log4j Exploit
    # 3 - WorldEdit
    # 4 - MultiverseCore
    # 5 - PEX
    Mode: 1
    PacketDelay: 100

BotSettings:
  # 可用占位符:
  # $rnd - 随机字符
  # $pwd - 随机生成密码
  BotName: "ImOldSix_$rnd"
  BotCount: 1000
  # 随机字符规则 (仅影响BotName):
  # 1 - Normal - 简单随机化
  # 2 - Ili - iii混淆式
  # 3 - ABC - 纯字母
  # 4 - 123 - 纯数字
  RandomFlag: 1
  RandomMinLength: 6
  RandomMaxLength: 8
  # 是否回复KeepAlive数据包
  # 如果你发现假人断开连接的原因与"Timeout"相关，请尝试切换此项。
  KeepAlive: false
  # 重新加入前模拟刷新服务器列表
  GetMotdBeforeRejoin: true
  GetMotdCount: 5
  GetMotdDelay: 500
  # 自动重连次数/间隔
  RejoinCount: 5
  RejoinDelay: 3500
  # 若踢出信息中检测到以下字段，则执行重连
  RejoinDetect:
    - "AntiAttack"
  # 若踢出信息为空，则无条件执行重连
  EmptyMsgRejoin: true
  # 若聊天信息中检测到以下字段，则尝试进行点击验证
  ClickVerifiesDetect:
    - "点击验证"
  # 支持占位符: $userName $rnd $pwd
  RegisterCommands:
    - "/register $pwd $pwd"
    - "/login $pwd"
  CustomChat:
    - "喵喵喵萌喵~ $rnd"
    - "喵喵喵萌~ $rnd"
    - "喵喵喵~ $rnd"
    - "喵喵~ $rnd"
    - "喵~ $rnd"
  # 显示来自服务器的聊天信息
  ShowServerMessages: true
  # 行动流程
  # async - 异步执行任务
  # wait - 等待:<时间(ms)>
  # chatSpam - 随机发送聊天信息:<次数>_<间隔(ms)>
  # randomTeleport - 随机传送:<次数>_<间隔(ms)>
  # backTeleport - 回到重生点
  # register&Login - 执行注册/登录:<flag>_<是否使用已生成密码>_<自定义密码>
  # crashPacket - 发送崩服数据包:<数量>
  # tabAttack - 执行Tab补全:<数量>_<间隔(ms)>
  Actions:
    - "register&Login:login_true_genshinImpact"
    - "async|chatSpam:10_3000"
    - "async|randomTeleport:25_100"
    - "wait:3000"
    - "async|backTeleport"
    - "async|crashPacket:75"
    - "async|tabAttack:25_75"

Proxy:
  # 代理获取方式:
  # 1 - API - 从API获取
  # 2 - File - 从本地读取
  # 3 - File + API - 两种方式同时获取
  GetType: 1
  # 代理类型:
  # 1 - HTTP/HTTPS
  # 2 - SOCKS4
  # 3 - SOCKS5
  ProxyType: 1
  UpdateTime: 300
  File: "proxies.txt"
  APIs:
    - "http://www.66ip.cn/mo.php?tqsl=9999"
    - "https://www.89ip.cn/tqdl.html?api=1&num=9999"
  # 保存能连接到目标服务器的代理地址 (如果支持)
  # 位置: working-proxies.txt
  SaveWorkingProxy: true