##############################
#  EndMinecraftPlusV2        #
#    Forked by SerendipityR  #
##############################

AttackSettings:
  Address: "example.com"
  Port: 25565
  # 攻击方式:
  # 1 - BotAttack - 集群假人(代理)
  # 2 - MotdAttackP - MOTD压测(代理)
  # 3 - MotdAttack - MOTD压测(无代理)
  # 4 - DoubleAttack - 影分身攻击(代理，仅原版单服可用)
  Method: 1
  Time: 3600
  ConnectDelay: 250
  # 实际连接数由代理质量和机器性能有关
  # 进行无代理Motd压测时不建议大于32
  MaxConnections: 2000
  # 旧版漏洞利用，大概率无效
  TabAttack: true
  AntiAttackMode: true
  DoubleExploitPlayer: "ImOldSix_666"

BotSettings:
  # 可用占位符:
  # $rnd - 随机字符
  # $pwd - 随机生成密码
  BotName: "ImOldSix_$rnd"
  BotCount: 1000
  RejoinCount: 5
  RejoinDelay: 2000
  RejoinDetect:
    - "AntiAttack"
  ClickVerifiesDetect:
    - "点击验证"
  Register&Login: true
  RegisterCommands:
    - "/register $pwd $pwd"
    - "/login $pwd"
  CustomChat:
    - "喵喵喵萌喵~ $rnd"
    - "喵喵喵萌~ $rnd"
    - "喵喵喵~ $rnd"
    - "喵喵~ $rnd"
    - "喵~ $rnd"
  ChatDelay: 3

Proxy:
  # 代理获取方式:
  # 1 - API - 从API获取
  # 2 - File - 从本地读取
  # 3 - File + API - 两种方式同时获取
  GetType: 1
  UpdateTime: 300
  File: "proxies.txt"
  APIs:
    - "http://www.66ip.cn/mo.php?tqsl=9999"
    - "https://www.89ip.cn/tqdl.html?api=1&num=9999"