##############################
#  EndMinecraftPlusV2        #
#    Forked by SerendipityR  #
##############################

CfgVer: 2

AttackSettings:
  Address: "example.com"
  Port: 25565
  # 攻击方式:
  # 1 - BotAttack - 集群假人(代理)
  # 2 - MotdAttack - MOTD压测(无代理)
  # 3 - MotdAttackP - MOTD压测(代理)
  # 4 - DoubleAttack - 影分身攻击(代理，仅原版单服可用)
  Method: 1
  Time: 3600
  ConnectDelay: 250
  ConnectTimeout: 8000
  # 实际连接数由代理质量和机器性能有关
  # 进行无代理Motd压测时不建议大于32
  MaxConnections: 2000
  # 旧版漏洞利用，大概率无效
  TabAttack: true
  AntiAttackMode: true
  DoubleExploitPlayer: "ImOldSix_666"
  ShowFails: false

BotSettings:
  # 可用占位符:
  # $rnd - 随机字符
  # $pwd - 随机生成密码
  BotName: "ImOldSix_$rnd"
  BotCount: 1000
  # 随机字符规则 (仅影响BotName):
  # 1 - Normal - 简单随机化
  # 2 - Ili - iii混淆式
  # 3 - ABC - 纯字母
  # 4 - 123 - 纯数字
  RandomFlag: 1
  RandomMinLength: 4
  RandomMaxLength: 6
  # 尝试发送随机传送数据包
  RandomTeleport: true
  RejoinCount: 5
  RejoinDelay: 2000
  RejoinDetect:
    - "AntiAttack"
  ClickVerifiesDetect:
    - "点击验证"
  Register&Login: true
  RegisterCommands:
    - "/register $pwd $pwd"
    - "/login $pwd"
  ChatSpam: true
  CustomChat:
    - "喵喵喵萌喵~ $rnd"
    - "喵喵喵萌~ $rnd"
    - "喵喵喵~ $rnd"
    - "喵喵~ $rnd"
    - "喵~ $rnd"
  ChatDelay: 3000

Proxy:
  # 代理获取方式:
  # 1 - API - 从API获取
  # 2 - File - 从本地读取
  # 3 - File + API - 两种方式同时获取
  GetType: 1
  # 代理类型:
  # 1 - HTTP/HTTPS
  # 2 - SOCKS4
  # 3 - SOCKS5
  ProxyType: 1
  UpdateTime: 300
  File: "proxies.txt"
  APIs:
    - "http://www.66ip.cn/mo.php?tqsl=9999"
    - "https://www.89ip.cn/tqdl.html?api=1&num=9999"
  # 保存能连接到目标服务器的代理地址 (如果支持)
  # 位置: working-proxies.txt
  SaveWorkingProxy: true